name: city
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - pyproj
  - rasterio
  - fiona
  - pyogrio
  - rtree
  - rasterstats
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - contextily
  - seaborn
  - osmnx
  - networkx
  - requests
  - tqdm
  - pyyaml
  - pyarrow
  - fastparquet
  - pillow
  - huggingface_hub
  - jupyterlab
  - ipykernel
